# Generated by Django 4.1.3 on 2022-12-06 14:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_users_date_users_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='data',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='lastname',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='user',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
