# Generated by Django 4.1.3 on 2022-12-06 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_users_data_alter_users_date_alter_users_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='id',
            new_name='uuid',
        ),
    ]
