# Generated by Django 4.1.3 on 2022-12-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_id_users_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='data',
            field=models.TextField(),
        ),
    ]
